In [36]:
import pandas as pd
import nltk
import numpy as np
import re
from nltk.stem import wordnet
from nltk import pos_tag
from nltk import word_tokenize
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import pairwise_distances

In [37]:
df = pd.read_excel(r'C:\Users\user\Desktop\bot kt\dialog_talk_bot.xlsx')
df.head(20)

                     Context                                    Text Response
0            Расскажи о себе                     Я могу быть твоим помощником
1   Я хочу узнать тебя лучше                    Я могу облегчить твою работу
2                Представься                                              NaN
3    Поделись фактами о себе                                              NaN
4                     Кто ты                                              NaN
5                     Что ты                                              NaN
6                        NaN                                              NaN
7         Каков твой возраст  Я довольно таки новый бот, созданный 09.12.2021
8           Сколько тебе лет                                              NaN
9         Какой твой возраст                                              NaN
10       Ты совершеннолетний                                              NaN
11   Сколько ты существуешь                                               NaN
12                       NaN                                              NaN
13            Ты раздражаешь                               Прости, я не хотел
14                 Ты бесишь  Я не думал, что могу доставить тебе неудобства
15             Ты так бесишь                                              NaN
16             Ты надоел мне                                              NaN
17         Ты так надоел мне                                              NaN
18                   Отстань                                              NaN
19                       NaN                                              NaN

In [38]:
df.ffill(axis=0, inplace = True)
df.head(20)

                     Context                                    Text Response
0            Расскажи о себе                     Я могу быть твоим помощником
1   Я хочу узнать тебя лучше                    Я могу облегчить твою работу
2                Представься                    Я могу облегчить твою работу
3    Поделись фактами о себе                    Я могу облегчить твою работу
4                     Кто ты                    Я могу облегчить твою работу
5                     Что ты                    Я могу облегчить твою работу
6                     Что ты                    Я могу облегчить твою работу
7         Каков твой возраст  Я довольно таки новый бот, созданный 09.12.2021
8           Сколько тебе лет  Я довольно таки новый бот, созданный 09.12.2021
9         Какой твой возраст  Я довольно таки новый бот, созданный 09.12.2021
10       Ты совершеннолетний  Я довольно таки новый бот, созданный 09.12.2021
11   Сколько ты существуешь   Я довольно таки новый бот, созданный 09.12.2021
12   Сколько ты существуешь   Я довольно таки новый бот, созданный 09.12.2021
13            Ты раздражаешь                               Прости, я не хотел
14                 Ты бесишь  Я не думал, что могу доставить тебе неудобства
15             Ты так бесишь  Я не думал, что могу доставить тебе неудобства
16             Ты надоел мне  Я не думал, что могу доставить тебе неудобства
17         Ты так надоел мне  Я не думал, что могу доставить тебе неудобства
18                   Отстань  Я не думал, что могу доставить тебе неудобства
19                   Отстань  Я не думал, что могу доставить тебе неудобства

In [39]:
df1 = df.head(10)
def step1(a):
    for x in a:
        b = str(x).lower()
        p = re.sub(r'[^а-я0-9]', ' ', b)
        print(p)

In [40]:
step1(df1['Context'])

расскажи о себе
я хочу узнать тебя лучше
представься
поделись фактами о себе
кто ты
что ты
что ты
каков твой возраст
сколько тебе лет
какой твой возраст

In [41]:
#nltk.download('punkt')
nltk.data.find(r'C:\Users\user\AppData\Roaming\nltk_data\tokenizers\punkt\russian.pickle')
s = 'Расскажи о себе'
words = word_tokenize(s)
print(words)

['Расскажи', 'о', 'себе']

In [42]:
#nltk.download('averaged_perceptron_tagger')
import pymorphy2
for i in words:
    p = morph.parse(i)[0]
    print(i,'-', p.tag.POS)
    
#lemma = wordnet.WordNetLemmatizer()
#pos_tag(nltk.word_tokenize(s), tagset = None)

NameError: name 'morph' is not defined

In [ ]:
import pymorphy2
morph = pymorphy2.MorphAnalyzer()

text = words

def lemmatize(text):

    res = list()
    for word in words:
        p = morph.parse(word)[0]
        res.append(p.normal_form)

    return res

print(lemmatize(text))

['рассказать', 'о', 'себя']

In [43]:
import nltk
#nltk.download("stopwords")
#--------#

from nltk.corpus import stopwords
from pymystem3 import Mystem
from string import punctuation

#Create lemmatizer and stopwords list
mystem = Mystem() 
russian_stopwords = stopwords.words("russian")

#Preprocess function
def text_normalization(text):
    tokens = mystem.lemmatize(text.lower())
    tokens = [token for token in tokens if token not in russian_stopwords\
              and token != " " \
              and token.strip() not in punctuation]
    
    text = " ".join(tokens)
    
    return text

In [44]:
text_normalization(s)

'рассказывать'

In [45]:
text_normalization('Что бы ты хотел сегодня поделать со мной')

'хотеть сегодня поделать'

In [46]:
df['Lemmatized'] = df['Context'].apply(text_normalization)
df.head(20)

,Context,Text Response,Lemmatized
0,Расскажи о себе,Я могу быть твоим помощником,рассказывать
1,Я хочу узнать тебя лучше,Я могу облегчить твою работу,хотеть узнавать
2,Представься,Я могу облегчить твою работу,представляться
3,Поделись фактами о себе,Я могу облегчить твою работу,поделиться факт
4,Кто ты,Я могу облегчить твою работу,
5,Что ты,Я могу облегчить твою работу,
6,Что ты,Я могу облегчить твою работу,
7,Каков твой возраст,"Я довольно таки новый бот, созданный 09.12.2021",каков твой возраст
8,Сколько тебе лет,"Я довольно таки новый бот, созданный 09.12.2021",сколько год
9,Какой твой возраст,"Я довольно таки новый бот, созданный 09.12.2021",твой возраст
10,Ты совершеннолетний,"Я довольно таки новый бот, созданный 09.12.2021",совершеннолетний
11,Сколько ты существуешь,"Я довольно таки новый бот, созданный 09.12.2021",сколько существовать
12,Сколько ты существуешь,"Я довольно таки новый бот, созданный 09.12.2021",сколько существовать
13,Ты раздражаешь,"Прости, я не хотел",раздражать
14,Ты бесишь,"Я не думал, что могу доставить тебе неудобства",бесить
15,Ты так бесишь,"Я не думал, что могу доставить тебе неудобства",бесить
16,Ты надоел мне,"Я не думал, что могу доставить тебе неудобства",надоедать
17,Ты так надоел мне,"Я не думал, что могу доставить тебе неудобства",надоедать
18,Отстань,"Я не думал, что могу доставить тебе неудобства",отставать
19,Отстань,"Я не думал, что могу доставить тебе неудобства",отставать

In [47]:
"""nltk.download('stopwords')"""
from nltk.corpus import stopwords
stop = stopwords.words('russian')
print(stop)

['и', 'в', 'во', 'не', 'что', 'он', 'на', 'я', 'с', 'со', 'как', 'а', 'то', 'все', 'она', 'так', 'его', 'но', 'да', 'ты', 'к', 'у', 'же', 'вы', 'за', 'бы', 'по', 'только', 'ее', 'мне', 'было', 'вот', 'от', 'меня', 'еще', 'нет', 'о', 'из', 'ему', 'теперь', 'когда', 'даже', 'ну', 'вдруг', 'ли', 'если', 'уже', 'или', 'ни', 'быть', 'был', 'него', 'до', 'вас', 'нибудь', 'опять', 'уж', 'вам', 'ведь', 'там', 'потом', 'себя', 'ничего', 'ей', 'может', 'они', 'тут', 'где', 'есть', 'надо', 'ней', 'для', 'мы', 'тебя', 'их', 'чем', 'была', 'сам', 'чтоб', 'без', 'будто', 'чего', 'раз', 'тоже', 'себе', 'под', 'будет', 'ж', 'тогда', 'кто', 'этот', 'того', 'потому', 'этого', 'какой', 'совсем', 'ним', 'здесь', 'этом', 'один', 'почти', 'мой', 'тем', 'чтобы', 'нее', 'сейчас', 'были', 'куда', 'зачем', 'всех', 'никогда', 'можно', 'при', 'наконец', 'два', 'об', 'другой', 'хоть', 'после', 'над', 'больше', 'тот', 'через', 'эти', 'нас', 'про', 'всего', 'них', 'какая', 'много', 'разве', 'три', 'эту', 'моя', 'впрочем', 'хорошо', 'свою', 'этой', 'перед', 'иногда', 'лучше', 'чуть', 'том', 'нельзя', 'такой', 'им', 'более', 'всегда', 'конечно', 'всю', 'между']

In [48]:
cv = CountVectorizer()
X = cv.fit_transform(df['Lemmatized']).toarray()

In [49]:
features = cv.get_feature_names()
df_bow = pd.DataFrame(X, columns = features)
df_bow.head(20)

C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,бесить,бумер,бумерский,возраст,вопрос,время,го,год,грустно,гуд,...,узнавать,уметь,услышать,учитель,факт,хороший,хотеть,часы,че,чувствовать
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [50]:
Quest = 'Ты бесишь меня каждым символом своего кода'

In [51]:
Q = []
a = Quest.split()
for i in a:
    if i in stop:
        continue
    else:
        Q.append(i)
    b = ' '.join(Q)
print (b)

Ты бесишь каждым символом своего кода

In [52]:
Quest_lemma = text_normalization(b)
Quest_bow = cv.transform([Quest_lemma]).toarray()
print(Quest_bow)

[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]

In [53]:
cosine_value = 1 - pairwise_distances(df_bow, Quest_bow, metric = 'cosine')
cosine_value

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [54]:
df['Simil_bow'] = cosine_value
df.head()

,Context,Text Response,Lemmatized,Simil_bow
0,Расскажи о себе,Я могу быть твоим помощником,рассказывать,0.0
1,Я хочу узнать тебя лучше,Я могу облегчить твою работу,хотеть узнавать,0.0
2,Представься,Я могу облегчить твою работу,представляться,0.0
3,Поделись фактами о себе,Я могу облегчить твою работу,поделиться факт,0.0
4,Кто ты,Я могу облегчить твою работу,,0.0

In [55]:
df_simi = pd.DataFrame(df, columns = ['Text Response', 'Simil_bow'])
df_simi.head()

                   Text Response  Simil_bow
0   Я могу быть твоим помощником        0.0
1  Я могу облегчить твою работу         0.0
2  Я могу облегчить твою работу         0.0
3  Я могу облегчить твою работу         0.0
4  Я могу облегчить твою работу         0.0

In [56]:
df_simi_sort = df_simi.sort_values(by = 'Simil_bow', ascending = False)
df_simi_sort.head()

                                      Text Response  Simil_bow
15  Я не думал, что могу доставить тебе неудобства         1.0
14  Я не думал, что могу доставить тебе неудобства         1.0
0                      Я могу быть твоим помощником        0.0
47               Давай, буду рад поболтать с тобой!        0.0
52               Давай, буду рад поболтать с тобой!        0.0

In [57]:
threshold = 0.2
df_tres = df_simi_sort[df_simi_sort['Simil_bow'] > threshold]
df_tres.tail()

                                      Text Response  Simil_bow
15  Я не думал, что могу доставить тебе неудобства         1.0
14  Я не думал, что могу доставить тебе неудобства         1.0

In [58]:
index_val = cosine_value.argmax()
df['Text Response'].loc[index_val]

'Я не думал, что могу доставить тебе неудобства '

In [59]:
Quest1 = 'Сколько тебе лет'

In [60]:
tfidf = TfidfVectorizer()
Quest1_lemma = text_normalization(Quest1)
print(Quest1_lemma)
#Quest1_tfidf = tfidf.transform([Quest1_lemma]).toarray()
Quest1_tfidf = tfidf.fit_transform([Quest1_lemma]).toarray()
print(Quest1_tfidf)

сколько год
[[0.70710678 0.70710678]]

In [61]:
x_tfidf = tfidf.fit_transform(df['Lemmatized']).toarray()
df_tfidf = pd.DataFrame(x_tfidf, columns = tfidf.get_feature_names())
df_tfidf.head()

C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,бесить,бумер,бумерский,возраст,вопрос,время,го,год,грустно,гуд,...,узнавать,уметь,услышать,учитель,факт,хороший,хотеть,часы,че,чувствовать
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.808964,0.0,0.0,0.0,0.000000,0.0,0.587859,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.707107,0.0,0.000000,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0

In [62]:
print(df['Lemmatized'])

0        рассказывать
1     хотеть узнавать
2      представляться
3     поделиться факт
4
           ...
66               окей
67                гуд
68              плохо
69            грустно
70       расстраивать
Name: Lemmatized, Length: 71, dtype: object

In [64]:
cos = 1 - pairwise_distances(df_tfidf, Quest1_tfidf, metric = 'cosine')
print(cos)

ValueError: Incompatible dimension for X and Y matrices: X.shape[1] == 59 while Y.shape[1] == 2

In [ ]:
df['sim_tfidf'] = cos
df_simi_tfidf = pd.DataFrame(df, columns = ['Text Response', 'sim_tfidf'])
df_simi_tfidf.head()

                   Text Response  sim_tfidf
0   Я могу быть твоим помощником        0.0
1  Я могу облегчить твою работу         0.0
2  Я могу облегчить твою работу         0.0
3  Я могу облегчить твою работу         0.0
4  Я могу облегчить твою работу         0.0

In [ ]:
df_simi_tfidf_sort = df_simi_tfidf.sort_values(by='sim_tfidf', ascending = False)
df_simi_tfidf_sort.head()

                         Text Response  sim_tfidf
0         Я могу быть твоим помощником        0.0
45                 Максим Вячеславович        0.0
51  Давай, буду рад поболтать с тобой!        0.0
50  Давай, буду рад поболтать с тобой!        0.0
49  Давай, буду рад поболтать с тобой!        0.0

In [ ]:
df_tresh = df_simi_tfidf_sort[df_simi_tfidf_sort['sim_tfidf'] > threshold]
df_tresh.head()

Empty DataFrame
Columns: [Text Response, sim_tfidf]
Index: []

In [ ]:
index_value = cos.argmax()
print(Quest1)
print(df['Text Response'].loc[index_value])

NameError: name 'cos' is not defined

In [ ]:
df['Context'].loc[index_value]

'Расскажи о себе'